import styles from './layout.module.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <header className={styles.layoutHeader}>
          <h1>Weather App</h1>
        </header>
        <main className={styles.main}>
          {children}
        </main>
      </body>
    </html>
  )
}
